### ISSUE TITLE
Implementing Breaking Changes for Improved API User Experience and Up-to-date Technical Documentation

### ISSUE THREAD

**Issue by arufars** [arufars/api-blue-archive#43]
## TODO
- [ ] Optimizing the API response messages to be more informative and user-friendly.
- [ ] Implementing improvements and changes to the API response that will differ from previous versions.
- [ ] Refactoring the code to improve performance and efficiency.
- [ ] Updating the technical documentation to facilitate understanding and implementation by other developers.
- [ ] Tagging the latest version in the API to track changes and improvements made.

**Comment by arufars** [comment]
https://linear.app/feat-blue-archive-api/issue/FEAT-11/new-docs-api-blue-archive

**Comment by arufars** [comment]
@arufars #77
